### ISSUE TITLE
Clear up access control and interplay between PaymentClient and PaymentProcessor

### ISSUE THREAD

**Issue by 0xNuggan** [InverterNetwork/inverter-contracts#199]
See audit: 
PP1. processPayments has no access restrictions [low]	
PP2. cancelRunningPayments access control is not suitable for its use [low]
VPP1. Anyone can steal payment orders funds of modules [high]	26
VPP2. Anyone can cancel payment orders of modules [high]

It's necessary to clarify the exact structure and access control of PaymentClients and PaymentProcessor. Some design decisions made in this regard (which can be revisited):
- **Anybody should be able to claim the funds they are owed without relying on third parties**. Right now this is made by having processPayments(IPaymentClient) be public. Another option would be to restrict processPayments() to be called from the client requesting to process the orders, and do it everytime one is added.
- **There can be several PaymentClients, but every Proposal will have only one PaymentProcessor**. This Processor should be able to handle all expected orders. In reverse, PaymentClients should make sure that the are deleting PaymentOrders only when they are transmitted to the proposal's PaymentProcessor.

**Comment by marvinkruse** [comment]
We might want to talk about this one, as we are not sure if this one is still relevant or will be fixed with the Role Authorizer changes
