### ISSUE TITLE
Security Review PR#350: Interface (Lib & ERC165Checker)

### ISSUE THREAD

**Issue by FHieser** [InverterNetwork/inverter-contracts#409]
https://linear.app/inverter/issue/SC-148/security-review-pr350-interface-lib-and-erc165checker

Link to comment(s)

Link PR comment, grouping them into one addressable issue if desired

https://github.com/InverterNetwork/inverter-contracts/pull/350#discussion_r1474555550

https://github.com/InverterNetwork/inverter-contracts/pull/350#discussion_r1479614870

Acceptance Criteria

Responded to comment with the purpose to signal agreement/rejection or discuss option moving forward

Implemented changes if applicable

**Comment by Zitzak** [comment]
Gm @FHieser , curious why you are not using the issue on Linear, or linking to it in the PR but instead duplicated it on Github

**Comment by FHieser** [comment]
Because I did forgot how to set up the connection properly in linear.
When I asked MarvinK about the other Issue that I tackled afterwards there was something wrong with the bridge to github and Marvin set it up for me, but afterwards it failed for me again for the 3rd issue.
I think it would help me if there was a "How to setup Issue thats linked to GitHub for Dummies" page that explains everything.
